Admin_Panel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='_admin_index_page'),
    path('articles/', views.ArticleListView.as_view(), name='_admin_article_list_page'),
    path('articles/edit/<pk>', views.ArticleEditView.as_view(), name='_admin_article_edit_page')
]

Article_Module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article_list_page'),
    path('cat/<str:category>', views.ArticleListView.as_view(), name='article_list_by_category'),
    path('add_article_comment', views.add_article_comment, name='add_article_comment'),
    path('<pk>/', views.ArticleDetailView.as_view(), name='article_detail_page')
]

Eshop_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home_Module.urls')),
    path('articles/', include('Article_Module.urls')),
    path('', include('Account_Module.urls')),
    path('contact-us/', include('Contact_Module.urls')),
    path('order/', include('Order_Module.urls')),
    path('products/', include('Product_Module.urls')),
    path('user/', include('User_Panel_Module.urls')),
    path('admin-panel/', include('Admin_Panel.urls'))
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Article_Module/models.py
from django.db import models
from jalali_date import date2jalali

from Account_Module.models import User


# Create your models here.


class ArticleCategory(models.Model):
    parent = models.ForeignKey('ArticleCategory', on_delete=models.CASCADE, null=True, blank=True,
                               verbose_name='دسته بندی والد')
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    url_title = models.CharField(max_length=200, unique=True, verbose_name='عنوان در url')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی مقاله'
        verbose_name_plural = 'دسته بندی های مقاله'


class Article(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=400, db_index=True, allow_unicode=True, verbose_name='عنوان در url')
    image = models.ImageField(upload_to='images/article', verbose_name='تصویر مقاله')
    short_description = models.TextField(verbose_name='توضیحات کوتاه')
    text = models.TextField(verbose_name='متن مقاله')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')
    selected_categories = models.ManyToManyField(ArticleCategory, verbose_name='دسته بندی ها')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نویسنده', null=True, editable=False)
    create_date = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='تاریخ ثبت')

    def __str__(self):
        return self.title

    def get_jalali_create_date(self):
        return date2jalali(self.create_date)

    def get_jalali_create_time(self):
        return self.create_date.strftime('%H:%M')

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'


class ArticleComments(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='مقاله')
    parent = models.ForeignKey('ArticleComments', on_delete=models.CASCADE, blank=True, null=True, verbose_name='والد')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    text = models.TextField(verbose_name='متن نظر')

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'نظر مقاله'
        verbose_name_plural = 'نظرات مقاله'

Article_Module/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Article, ArticleCategory, ArticleComments


# Create your views here.

class ArticleListView(ListView):
    template_name = 'Article_Module/article-list.html'
    model = Article
    paginate_by = 4

    def get_queryset(self):
        query = super().get_queryset()
        category_name = self.kwargs.get('category')
        query = query.filter(is_active=True)
        if category_name is not None:
            query = query.filter(selected_categories__url_title__iexact=category_name)
        return query


class ArticleDetailView(DetailView):
    template_name = 'Article_Module/article_detail.html'
    model = Article

    def get_queryset(self):
        query = super().get_queryset()
        query = query.filter(is_active=True)
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article: Article = kwargs.get('object')
        context['comments'] = ArticleComments.objects.filter(article_id=article.id, parent_id=None).order_by(
            '-create_date').prefetch_related('articlecomments_set')
        context['all_comments'] = ArticleComments.objects.filter(article_id=article.id).count()
        return context


def article_category_component(request):
    article_main_category = ArticleCategory.objects.filter(is_active=True, parent_id=None)
    context = {
        'article_main_category': article_main_category
    }
    return render(request, 'Article_Module/component/article_category_component.html', context)


def add_article_comment(request):
    if request.user.is_authenticated:
        article_id = request.GET.get('article_id')
        article_comment = request.GET.get('article_comment')
        parent_id = request.GET.get('parent_id')
        new_comment = ArticleComments(
            article_id=article_id,
            text=article_comment,
            user_id=request.user.id,
            parent_id=parent_id
        )
        new_comment.save()
        context = {
            'comments': ArticleComments.objects.filter(article_id=article_id, parent_id=None).order_by(
                '-create_date').prefetch_related('articlecomments_set'),
            'all_comments': ArticleComments.objects.filter(article_id=article_id).count()
        }
        return render(request, 'Article_Module/includes/article_comments_partial.html', context)
    return HttpResponse('response')

Article_Module/templates/Article_Module/component/article_category_component.html
<h2>دسته بندی محصولات</h2>
<div class="panel-group category-products" id="accordian"><!--category-productsr-->
    {% for main_category in article_main_category %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    {% if main_category.articlecategory_set.all %}
                        <a data-toggle="collapse" data-parent="#accordian" href="#{{ main_category.url_title }}">
                            <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                            {{ main_category.title }}
                        </a>
                    {% else %}
                        <a href="{% url 'article_list_by_category' category=main_category.url_title %}">{{ main_category.title }}</a>
                    {% endif %}
                </h4>
            </div>
            {% if main_category.articlecategory_set.all %}
                <div id="{{ main_category.url_title }}" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul>
                            <li><a href="{% url 'article_list_by_category' category=main_category.url_title %}"> نمایش تمامی محصولات  {{ main_category.title }}</a></li>
                            {% for sub_category in main_category.articlecategory_set.all %}
                                {% if sub_category.is_active %}
                                    <li><a href="{% url 'article_list_by_category' category=sub_category.url_title %}"> {{ sub_category.title }} </a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endif %}
        </div>
    {% endfor %}

</div><!--/category-productsr-->